---
# tasks file for nginx-setup
- name: Install nginx
  package: 
    name: '{{packages["nginx"]}}'
  become: true
- name: Remove default config
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: Define directory names
  set_fact:
    backup_dir: /tmp/nginx_backups
    optional_snippet_dir: /etc/nginx/sites-enabled/snippets/optional.d/
- name: Create backup directory
  file:
    path: '{{backup_dir}}'
    state: directory
- name: Define remote facts
  set_fact:
    conf_name: '{{app_prefix}}'
    env_choice: remote
  when: ansible_host not in ["127.0.0.1", "localhost"] and not "192.168.0.0/16"|ansible.utils.network_in_usable(ansible_host)
- name: Define vm facts
  set_fact:
    conf_name: '{{app_prefix}}'
    env_choice: vm
  when: ansible_host not in ["127.0.0.1", "localhost"] and "192.168.0.0/16"|ansible.utils.network_in_usable(ansible_host)
- name: Define local facts
  set_fact:
    conf_name: '{{app_prefix}}_{{env_name}}'
    env_choice: local
  when: ansible_host in ["127.0.0.1", "localhost"]
- name: Define config locations
  set_fact:
    configs:
      root:
        path: '{{root_config}}'
        backup: '{{backup_dir}}/root'
      security:
        path: /etc/nginx/sites-enabled/snippets/security.conf
        backup: '{{backup_dir}}/security'
      app_common:
        path: '/etc/nginx/sites-enabled/{{conf_name}}.conf'
        backup: '{{backup_dir}}/{{conf_name}}'
      app_snippets:
        path: '{{optional_snippet_dir}}/{{conf_name}}'
        backup: '{{backup_dir}}/{{conf_name}}.snippet'
- name: Create snippets directory
  become: true
  file:
    path: '{{optional_snippet_dir}}'
    state: directory
- name: Tasks for a local server
  include_tasks: local.yml
  vars:
    __conf_name_ngx__: '{{configs["app_common"]["path"]}}'
    __env_name_ngx__: '{{env_name}}'
    __common_name_ngx__: '{{common_name}}'
    __sec_snippets_ngx__: '{{configs["security"]["path"]}}'
    __optional_snippets_ngx__: '{{optional_snippet_dir}}'
  when: env_choice == "local"

- name: VM setup
  include_tasks: vm.yml
  vars:
    __conf_name_ngx__: '{{configs["app_common"]["path"]}}'
    __cert_prefix_ngx__: '{{app_prefix}}'
    __common_name_ngx__: '{{common_name}}'
    __sec_snippets_ngx__: '{{configs["security"]["path"]}}'
    __optional_snippets_ngx__: '{{optional_snippet_dir}}'
  when: env_choice == "vm"

- name: Remote setup
  include_tasks: remote.yml
  vars:
    __conf_name_ngx__: '{{configs["app_common"]["path"]}}'
    __cert_prefix_ngx__: '{{app_prefix}}'
    __server_name_ngx__: '{{server_name}}'
    __keys_ngx__: 
      pb_api_key: '{{keys["pb_api_key"]}}'
      pb_secret: '{{keys["pb_secret"]}}'
    __sec_snippets_ngx__: '{{configs["security"]["path"]}}'
    __optional_snippets_ngx__: '{{optional_snippet_dir}}'
  when: env_choice == "remote"
- name: Root config 
  include_tasks: root_config.yml
  vars:
    __root_config__: '{{configs["root"]["path"]}}'
- name: Manually copy configs
  copy:
    remote_src: true
    src: '{{ngx_file["value"]["path"]}}'
    dest: '{{ngx_file["value"]["backup"]}}'
  failed_when: false
  loop: '{{configs | dict2items}}'
  loop_control:
    loop_var: ngx_file
    label: '{{ngx_file["key"]}}'
- name: Safely replace app specific config
  block:
    - name: Replace app Specific config
      become: true
      template: 
        src: nginx_template.j2
        dest: '{{configs["app_snippets"]["path"]}}'
      notify: Restart nginx
      register:
        updated
    - name: Run validation
      command: 'nginx -t'
      become: true
      when: updated is changed
  rescue:
    - name: Restore old configs manually
      copy:
        remote_src: true
        src: '{{item["value"]["backup"]}}'
        dest: '{{item["value"]["path"]}}'
      failed_when: false
      loop: '{{configs | dict2items}}'
      loop_control:
        label: '{{item["key"]}}'
      when: updated is changed
    - name: End playbook
      fail: 
        msg: "nginx validation failed"
      when: updated is changed
  always:
    - name: Manually clean up backup configs
      file:
        path: '{{ngx_file["value"]["backup"]}}'
        state: absent
      failed_when: false
      loop: '{{configs | dict2items}}'
      loop_control:
        loop_var: ngx_file
        label: '{{ngx_file["key"]}}'
      when: updated is changed


