#SPDX-License-Identifier: MIT-0
---
# tasks file for prometheus-setup
- name: Install fail2ban
  package: 
    name: '{{packages["fail2ban"]}}'
  become: true
- name: Tweak sshd scanning
  blockinfile:
      path: /etc/fail2ban/jail.d/sshd-journal-fix.conf
      marker: '# {mark} ANSIBLE - ssh ban'
      block: |
        [sshd]
        backend = systemd
        journalmatch = _SYSTEMD_UNIT=ssh.service
      create: true
  become: true
  notify: Restart fail2ban
  when: ansible_os_family == "Debian"